on:
  push:
    branches:
      - main

name: Linux_Container_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/calendar:${{ github.sha }} --build-arg PROD_ENV="NEXT_PUBLIC_STORAGE_ACCOUNT=${{ vars.STORAGE_ACCOUNT}}\nNEXT_PUBLIC_STORAGE_TOKEN=${{ secrets.STORAGE_TOKEN}}"
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/calendar:${{ github.sha }}

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: sswecal
          containerAppName: sswecalca
          resourceGroup: SS-WE-CAL-CA_group
          imageToDeploy: sswecal.azurecr.io/calendar:${{ github.sha }}
